#!/bin/sh
#
# App        Starts .
#

umask 077

start() {
	printf "Starting App: "
	source /etc/profile
	/opt/start_ap &
	/opt/beep
	/opt/app &
	echo "OK"
}
stop() {
	printf "Stopping App: "
	killall app 
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

